---
version: '2.1'
services:

  # Fully functional local AWS cloud stack: https://github.com/localstack/localstack
  localstack:
    image: localstack/localstack:0.8.7
    container_name: localstack
    environment:
      SERVICES: dynamodb:6000,kinesis:7000
      DEFAULT_REGION: us-east-1
      PORT_WEB_UI: 8080
    #   DATA_DIR: /tmp/localstack/data # Leave blank to disable persistence
    # volumes:
    #   - "${TMPDIR:-/tmp/localstack}:/tmp/localstack"
    ports:
      - "6000:6000"
      - "7000:7000"

  # Zookeeper: https://hub.docker.com/r/confluentinc/cp-zookeeper/
  zookeeper:
    image: confluentinc/cp-zookeeper:${CONFLUENT_VERSION}
    container_name: zookeeper
    hostname: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  # Kafka with SSL:
  kafka:
    image: confluentinc/cp-kafka:${CONFLUENT_VERSION}
    container_name: kafka
    hostname: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LOG_CLEANER_ENABLE: 'true'
      KAFKA_CLEANUP_POLICY: delete
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_CONFLUENT_SUPPORT_CUSTOMER_ID: anonymous
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: SSL://kafka:9093
      KAFKA_SSL_KEYSTORE_FILENAME: ${KEYSTORE_FILENAME}
      KAFKA_SSL_KEYSTORE_CREDENTIALS: ${KEYSTORE_CRED_FILENAME}
      KAFKA_SSL_TRUSTSTORE_FILENAME: ${TRUSTSTORE_FILENAME}
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: ${TRUSTSTORE_CRED_FILENAME}
      KAFKA_SSL_KEY_CREDENTIALS: ${SSL_KEY_CRED_FILENAME}
      KAFKA_SSL_ENABLED_PROTOCOLS: TLSv1.2
      KAFKA_SECURITY_INTER_BROKER_PROTOCOL: SSL
      KAFKA_SSL_CLIENT_AUTH: required
      KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.auth.SimpleAclAuthorizer
      KAFKA_SUPER_USERS: ${CERTIFICATE_AUTHORITY}
    volumes:
      - ${LOCAL_SSL_DIR}:/etc/kafka/secrets
    ports:
      - "9093:9093"

  # Schema Registry
  schema-registry:
    image: confluentinc/cp-schema-registry:${CONFLUENT_VERSION}
    container_name: schema-registry
    hostname: schema-registry
    depends_on:
      - zookeeper
      - kafka
    environment:
      SCHEMA_REGISTRY_AVRO_COMPATIBILITY_LEVEL: full_transitive
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: SSL://kafka:9093
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_LOCATION: /etc/kafka/secrets/${KEYSTORE_FILENAME}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEYSTORE_PASSWORD: ${KEYSTORE_PASSWORD}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_LOCATION: /etc/kafka/secrets/${TRUSTSTORE_FILENAME}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_TRUSTSTORE_PASSWORD: ${TRUSTSTORE_PASSWORD}
      SCHEMA_REGISTRY_KAFKASTORE_SSL_KEY_PASSWORD: ${SSL_KEY_PASSWORD}
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: SSL
      SCHEMA_REGISTRY_KAFKASTORE_SSL_ENABLED_PROTOCOLS: TLSv1.2
    volumes:
      - ${LOCAL_SSL_DIR}:/etc/kafka/secrets
    ports:
      - "8081:8081"
